Indexação em Arrays NumPy

In [1]:
# Importando a biblioteca
import numpy

Indexação em Arrays Numpy

In [2]:
arra1 = numpy.array([10, 21, 32, 43, 15, 76, 57, 89])

In [3]:
print(arra1)

[10 21 32 43 15 76 57 89]


In [4]:
# Imprimindo um elementro específico no array
print(arra1[4])

15


In [5]:
# Indexação
arra1[1:4]

array([21, 32, 43])

In [6]:
# Criando uma lista de indices
indices = [1, 2, 5, 6]

In [7]:
# Imprimindo elementos dos índices
arra1[indices]

array([21, 32, 76, 57])

In [8]:
# Criando uma mascara booleana para os elementos pares
mask = (arra1 % 2 == 0)

In [9]:
# Exibindo os valores da mascara
print(mask)

[ True False  True False False  True False False]


In [10]:
# Exibindo somentos os valores Trues na lista
arra1[mask]

array([10, 32, 76])

In [ ]:
# Alterando um elemento do array
arra1[0] = 100
print(arra1)

In [ ]:
# não é possivel incluir elemento de outro tipo
try:
    arra1[0] = 'Novo elemento'
except:
    print("Operação não permitida")