### Funções em Numpy

In [1]:
# importando a Biblioteca
import numpy

In [2]:
# A função array() cria um array Numpy
arr2 = numpy.array([1, 2, 3, 4, 5])

In [3]:
print(arr2)

[1 2 3 4 5]


In [4]:
# Verificando o tipo do objeto
type(arr2)

numpy.ndarray

Usando métodos do Array Numpy

In [5]:
# A função cumsum() (cumulative sum) calcula a soma cumulativa dos elementos 
# de um array. Isso significa que cada elemento do array resultante é a soma 
# de todos os elementos anteriores, incluindo o próprio elemento.
arr2.cumsum()

array([ 1,  3,  6, 10, 15])

In [6]:
# A função cumprod() (cumulative product) funciona de forma muito semelhante à cumsum(),
# mas em vez de somar os elementos, ela os multiplica. Cada elemento do array resultante 
# é o produto de todos os elementos anteriores, incluindo o próprio elemento.
arr2.cumprod()

array([  1,   2,   6,  24, 120])

In [7]:
# A função arange cria um array NumPy contendo uma progressão aritmética a partir 
# de um intervalo — start, stop, Step.
arr3 = numpy.arange(0,50,5)
print(arr3)

[ 0  5 10 15 20 25 30 35 40 45]


In [8]:
# Verificando o tipo do objeto
type(arr3)

numpy.ndarray

In [9]:
# Formato do array
numpy.shape(arr3)

(10,)